CHITTER_JAVA_JWT_KEY: jwt-key

server:
  port: '8084'

spring:
  application:
    name: test-inditex
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: userind
    url: jdbc:h2:mem:dev_inditex
  r2dbc:
    url: r2dbc:h2:mem:///dev_inditex
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
    root: WARN
